-- liquibase formatted sql

-- changeset andre:1749221185318-1
CREATE TABLE loturi
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nume_produs       VARCHAR(255)                            NOT NULL,
    tip_produs_id     BIGINT,
    descriere         VARCHAR(255)                            NOT NULL,
    cantitate         BIGINT DEFAULT 0                        NOT NULL,
    cantitate_vanduta BIGINT DEFAULT 0                        NOT NULL,
    localizare        VARCHAR(255),
    numar             BIGINT DEFAULT 0                        NOT NULL,
    data_expirare     date                                    NOT NULL,
    furnizor          VARCHAR(255),
    CONSTRAINT pk_loturi PRIMARY KEY (id)
);

-- changeset andre:1749221185318-2
CREATE TABLE tipuri_produs
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nume VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_tipuri_produs PRIMARY KEY (id)
);

-- changeset andre:1749221185318-3
CREATE TABLE utilizatori
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nume_de_utilizator VARCHAR(255)                            NOT NULL,
    parola             VARCHAR(255)                            NOT NULL,
    este_admin         BOOLEAN DEFAULT FALSE,
    CONSTRAINT pk_utilizatori PRIMARY KEY (id)
);

-- changeset andre:1749221185318-4
CREATE TABLE vanzari
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    lot_id  BIGINT,
    data    date                                    NOT NULL,
    vanzari BIGINT                                  NOT NULL,
    CONSTRAINT pk_vanzari PRIMARY KEY (id)
);

-- changeset andre:1749221185318-5
ALTER TABLE loturi
    ADD CONSTRAINT uc_loturi_numar UNIQUE (numar);

-- changeset andre:1749221185318-6
ALTER TABLE utilizatori
    ADD CONSTRAINT uc_utilizatori_numedeutilizator UNIQUE (nume_de_utilizator);

-- changeset andre:1749221185318-7
ALTER TABLE loturi
    ADD CONSTRAINT FK_LOTURI_ON_TIPPRODUS FOREIGN KEY (tip_produs_id) REFERENCES tipuri_produs (id);

-- changeset andre:1749221185318-8
ALTER TABLE vanzari
    ADD CONSTRAINT FK_VANZARI_ON_LOT FOREIGN KEY (lot_id) REFERENCES loturi (id);

